remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: UUIDv7 Generator
description: Geerate UUIDv7 online
show_downloads: false
#google_analytics: id
